#!/bin/bash
echo "Running..."
#check uid
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root. Aborting."
    exit 1
fi
cd /sys/class/leds
# Change wd
file=$(ls *::scrolllock/brightness)
#Set file
echo "0" > "$file"
echo "Script complete."
